"""Creation de la table car

Revision ID: b51b1ddf9558
Revises: 76fd489aa49b
Create Date: 2024-04-09 19:39:33.802761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b51b1ddf9558'
down_revision: Union[str, None] = '76fd489aa49b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('marque', sa.String(length=150), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=True),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('is_disponible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=False)
    op.create_index(op.f('ix_cars_is_disponible'), 'cars', ['is_disponible'], unique=False)
    op.create_index(op.f('ix_cars_marque'), 'cars', ['marque'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cars_marque'), table_name='cars')
    op.drop_index(op.f('ix_cars_is_disponible'), table_name='cars')
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.drop_table('cars')
    # ### end Alembic commands ###
